# Generated by Django 4.2.6 on 2023-11-28 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='user_auth',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employe_user_auth', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
