# Generated by Django 4.2.6 on 2023-11-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_propriete_image_delete_caracteristique'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propriete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
