# Generated by Django 4.2.6 on 2023-11-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tell',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
