# Generated by Django 4.2.6 on 2023-11-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='adresse',
            field=models.CharField(max_length=30),
        ),
    ]
