# Generated by Django 4.2.6 on 2023-11-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_propriete_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='caracteristiques/'),
        ),
        migrations.DeleteModel(
            name='Caracteristique',
        ),
    ]
