# Generated by Django 4.2.6 on 2023-11-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='adresse',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='password',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employe',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
